import { resolve, sep } from "node:path";
import { readFileSync, realpathSync } from "node:fs";
import { StringEnum } from "@earendil-works/pi-ai";
import { defineTool, type ToolDefinition } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";
import type { AgentTree } from "../agent-tree.js";
import type { ResearchMemory } from "../research-memory.js";
import type { ExperimentRunner } from "./experiment.js";
import type { WebGateway } from "./web.js";

interface ToolDeps { tree: AgentTree; parentId: string; memory: ResearchMemory; web: WebGateway; experiments: ExperimentRunner; cwd: string }
const text = (value: unknown, details: unknown = {}) => ({ content: [{ type: "text" as const, text: typeof value === "string" ? value : JSON.stringify(value, null, 2) }], details });
export function confined(root: string, path: string): string {
  const absolute = resolve(root, path);
  let real = absolute; let realRoot = root;
  try { real = realpathSync(absolute); realRoot = realpathSync(root); } catch { /* file may not exist; the lexical check below still applies */ }
  if (real !== realRoot && !real.startsWith(`${realRoot}${sep}`)) throw new Error("Path escapes the allowed project/state directory");
  return absolute;
}

export function createResearchTools(deps: ToolDeps): ToolDefinition[] {
  const spawn = defineTool({
    name: "spawn_agent", label: "Spawn research agent", description: "Create a dynamically specialized child AgentSession. Every child receives this tool and may recurse within coded limits.",
    promptSnippet: "Spawn a specialized recursive research child", promptGuidelines: ["Use spawn_agent only for a concrete, non-duplicate specialized task with an expected output and completion criterion. Mark independent replications explicitly."],
    parameters: Type.Object({ name: Type.String({ minLength: 2 }), role: Type.String({ minLength: 3 }), task: Type.String({ minLength: 12 }), expected_output: Type.String({ minLength: 3 }), completion_criteria: Type.String({ minLength: 3 }), context: Type.Optional(Type.String()), responsibilities: Type.Optional(Type.String()), tools: Type.Optional(Type.Array(Type.String())), background: Type.Optional(Type.Boolean({ default: true })), replication_of: Type.Optional(Type.String()), independent_context: Type.Optional(Type.Boolean()) }),
    async execute(_id, params, _signal, _update, ctx) { const record = await deps.tree.spawn({ parentId: deps.parentId, name: params.name, role: params.role, task: params.task, expectedOutput: params.expected_output, completionCriteria: params.completion_criteria, ...(params.context ? { context: params.context } : {}), ...(params.responsibilities ? { responsibilities: params.responsibilities } : {}), ...(params.tools ? { tools: params.tools } : {}), background: params.background ?? true, ...(params.replication_of ? { replicationOf: params.replication_of } : {}), ...(params.independent_context !== undefined ? { independentContext: params.independent_context } : {}) }, { model: ctx.model ? `${ctx.model.provider}/${ctx.model.id}` : "inherit", thinkingLevel: ctx.thinkingLevel ?? "inherit" }); if (params.background === false) return text(await deps.tree.start(record.id), { agentId: record.id }); return text({ agentId: record.id, status: "running", depth: record.depth, parent: record.parentId }, { agentId: record.id }); },
  });
  const control = defineTool({
    name: "agent_control", label: "Agent tree control", description: "List, inspect, wait for, message, steer, cancel, or collect another agent.",
    parameters: Type.Object({ action: StringEnum(["list", "inspect", "start", "wait", "steer", "follow_up", "report_parent", "cancel", "cancel_branch", "collect"] as const), agent_id: Type.Optional(Type.String()), message: Type.Optional(Type.String()) }),
    async execute(_id, params) { if (params.action === "list") return text(deps.tree.list()); if (params.action === "report_parent") { if (!params.message) throw new Error("message is required"); const parent = deps.tree.inspect(deps.parentId).parentId ?? deps.tree.rootId; await deps.tree.message(parent, params.message, deps.parentId); return text("Reported to parent"); } if (!params.agent_id) throw new Error("agent_id is required"); if (params.action === "inspect") return text(deps.tree.inspect(params.agent_id)); if (params.action === "start") return text(await deps.tree.start(params.agent_id)); if (params.action === "wait") return text(await deps.tree.wait(params.agent_id)); if (params.action === "collect") return text(deps.tree.collectResult(params.agent_id) ?? { status: deps.tree.inspect(params.agent_id).status }); if (params.action === "steer") { if (!params.message) throw new Error("message is required"); await deps.tree.steer(params.agent_id, params.message); } else if (params.action === "follow_up") { if (!params.message) throw new Error("message is required"); await deps.tree.followUp(params.agent_id, params.message); } else if (params.action === "cancel") await deps.tree.cancel(params.agent_id); else await deps.tree.cancelBranch(params.agent_id); return text("OK"); },
  });
  const memorySearch = defineTool({ name: "search_memory", label: "Search research memory", description: "Full-text search synthesized findings, hypotheses, questions, and negative results.", parameters: Type.Object({ query: Type.String(), limit: Type.Optional(Type.Integer({ minimum: 1, maximum: 50 })) }), async execute(_id, params) { return text(deps.memory.search(params.query, params.limit ?? 10)); } });
  const publish = defineTool({ name: "publish_finding", label: "Publish finding", description: "Persist an atomic sourced finding in Markdown and the rebuildable FTS index.", parameters: Type.Object({ type: StringEnum(["fact", "inference", "hypothesis", "counterargument", "experiment_result", "open_question"] as const), status: StringEnum(["observed", "corroborated", "contested", "inferred", "hypothetical", "tested", "rejected", "outdated"] as const), title: Type.String(), statement: Type.String(), evidence: Type.Optional(Type.String()), counterevidence: Type.Optional(Type.String()), limitations: Type.Optional(Type.String()), sources: Type.Optional(Type.Array(Type.String())), related: Type.Optional(Type.Array(Type.String())), negative_result: Type.Optional(Type.Boolean()) }), async execute(_id, params) { const id = deps.memory.save({ type: params.type, status: params.status, createdBy: deps.parentId, runId: deps.tree.runId, title: params.title, statement: params.statement, ...(params.evidence ? { evidence: params.evidence } : {}), ...(params.counterevidence ? { counterevidence: params.counterevidence } : {}), ...(params.limitations ? { limitations: params.limitations } : {}), ...(params.sources ? { sources: params.sources } : {}), ...(params.related ? { related: params.related } : {}), ...(params.negative_result !== undefined ? { negativeResult: params.negative_result } : {}) }); return text({ id }); } });
  const readArtifact = defineTool({ name: "read_artifact", label: "Read project artifact", description: "Read a UTF-8 artifact confined to the project directory.", parameters: Type.Object({ path: Type.String() }), async execute(_id, params) { const path = confined(deps.cwd, params.path); return text(readFileSync(path, "utf8")); } });
  const webSearch = defineTool({ name: "web_search", label: "Local web search", description: "Search through local SearXNG.", parameters: Type.Object({ query: Type.String(), limit: Type.Optional(Type.Integer()) }), async execute(_id, params) { return text(await deps.web.search(params.query, params.limit ?? 10)); } });
  const webRead = defineTool({ name: "web_read", label: "Read web page", description: "Read a public page through self-hosted Firecrawl and preserve it as an untrusted source.", parameters: Type.Object({ url: Type.String(), refresh: Type.Optional(Type.Boolean()) }), async execute(_id, params) { return text(await deps.web.read(params.url, params.refresh ?? false)); } });
  const webCrawl = defineTool({ name: "web_crawl", label: "Crawl web site", description: "Start a bounded crawl through self-hosted Firecrawl.", parameters: Type.Object({ url: Type.String(), limit: Type.Optional(Type.Integer()) }), async execute(_id, params) { return text(await deps.web.crawl(params.url, params.limit ?? 20)); } });
  const webBrowse = defineTool({ name: "web_browse", label: "Interactive browser fallback", description: "Use the configured local Browser Use adapter for an interactive public page.", parameters: Type.Object({ url: Type.String(), task: Type.String() }), async execute(_id, params) { return text(await deps.web.browse(params.url, params.task)); } });
  const download = defineTool({ name: "download_source", label: "Download source", description: "Download, hash, validate, deduplicate, and preserve a public source.", parameters: Type.Object({ url: Type.String() }), async execute(_id, params) { return text(await deps.web.downloadSource(params.url)); } });
  const experiment = defineTool({ name: "run_experiment", label: "Run isolated experiment", description: "Run a frozen test plan and generated source in a networkless, resource-limited Docker container. Never falls back to host execution.", executionMode: "sequential" as const, parameters: Type.Object({ plan: Type.Object({ hypothesis: Type.String(), data: Type.String(), baseline: Type.String(), split: Type.String(), metrics: Type.Array(Type.String()), successCriterion: Type.String(), refutationCriterion: Type.String(), confounders: Type.Array(Type.String()), resourceLimits: Type.String() }), command: Type.String(), source_files: Type.Record(Type.String(), Type.String()), data_manifest: Type.Optional(Type.Unknown()), image: Type.Optional(Type.String()) }), async execute(_id, params) { return text(await deps.experiments.run({ plan: params.plan, command: params.command, sourceFiles: params.source_files, createdBy: deps.parentId, ...(params.data_manifest !== undefined ? { dataManifest: params.data_manifest } : {}), ...(params.image ? { image: params.image } : {}) })); } });
  const reviewExperiment = defineTool({ name: "review_experiment", label: "Review experiment independently", description: "Record an independent verdict for a frozen experiment. The experiment author cannot review their own work.", executionMode: "sequential" as const, parameters: Type.Object({ experiment_id: Type.String(), verdict: StringEnum(["supported", "partially_supported", "inconclusive", "contradicted", "invalid_experiment", "requires_external_validation"] as const), summary: Type.String(), limitations: Type.String() }), async execute(_id, params) { const authorId = deps.experiments.authorOf(params.experiment_id); const reviewer = deps.tree.inspect(deps.parentId); if (reviewer.lineage.includes(authorId)) throw new Error("Independent review must be performed by an agent that is not a descendant of the experiment author"); return text(deps.experiments.review({ experimentId: params.experiment_id, reviewerId: deps.parentId, verdict: params.verdict, summary: params.summary, limitations: params.limitations })); } });
  return [spawn, control, memorySearch, publish, readArtifact, webSearch, webRead, webCrawl, webBrowse, download, experiment, reviewExperiment];
}
